## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d=np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list=[1,2,3]
print("Python list multiplication ",py_list*2)

np_array=np.array([1,2,3])
print("Python array multiplication ",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)
print("\n Numpy operation time: ",time.time()-start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.05100440979003906

 Numpy operation time:  0.0010001659393310547


### creating array from scratch

In [4]:
zeroes=np.zeros((3,4))
print("zeros array: \n",zeroes)

ones=np.ones((2,3))
print("ones array: \n",ones)

full_arr=np.full((3,4),5)
print("full array: \n",full_arr)

random_arr=np.random.random((4,5))
print("random array: \n",random_arr)


seq=np.arange(0,11,2)
print("sequence array: \n",seq)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array: 
 [[4.46484453e-03 9.02083947e-01 5.58778524e-01 2.16009349e-01
  5.50459670e-01]
 [5.50799680e-01 1.77802382e-05 9.23818662e-01 4.98516480e-01
  9.60879280e-01]
 [5.86739077e-01 2.34830356e-01 4.21781114e-01 1.25478533e-01
  3.13966960e-01]
 [6.17340512e-01 8.33735767e-01 6.24346388e-01 4.13528488e-01
  6.77058976e-01]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector,Matrices and Tensor

In [5]:
vector=np.array([1,2,3,4,5])
print("vector: ",vector)

matrices=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Matrices: ",matrices)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor: ",tensor)

vector:  [1 2 3 4 5]
Matrices:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape     ",arr.shape)
print("Dimension ",arr.ndim)
print("Size      ",arr.size)
print("DType     ",arr.dtype)

Shape      (2, 3)
Dimension  2
Size       6
DType      int64


### Array Reshaping

In [7]:
arr=np.arange(12)
print("Original Array:\n",arr)

reshaped=arr.reshape((3,4))
print("\n Reshaped Array:\n",reshaped)

flattened=reshaped.flatten()
print("\n Flattened Array:\n",flattened)

# ravel returns view, instead of copy
raveled=reshaped.ravel()
print("\nRaveled array:\n",raveled)

# Transpose
transpose=reshaped.T
print("\ntransposed array:\n",transpose)


Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
